{
    'name': "product_fields",
    'version': "19.0.1.2",
    'category': 'Technical',
    'summary': """ Creating a new field for choosing brand of an product""",
    'description': """Creating a new field for choosing brand of an product and displaying the field values in sale orderline product list view  """,
    'depends': ['base','sale','product'],
    'data': ["security/ir.model.access.csv",
             "data/product_product_brand.xml",
             "views/product_product.xml",
             "views/res_partner.xml",
             "views/sale_order.xml",
             "views/account_move_line.xml",
             ],
    'author': "demo company",
    'website': "https://www.demo_company.com",
    'sequence': -10,
    'application': True,
    'installable': True,
    'auto_install': True,
}
