{
    'name': "machine_management",
    'version': "19.0.1.2",
    'category': 'Technical',
    'summary': """Fast services for machine management """,
    'description': """Complete Solution for an Machines Management """,
    'depends': ['base','sale','mail','product'],
    'data': ["security/ir.model.access.csv",
             "security/security_groups.xml",
             "data/service_product.xml",
             "data/machine_machine_tags.xml",
             "data/machine_sequence.xml",
            "data/machine_machine_types.xml",
             "data/mail_template_machine.xml",
             "data/ir_cron_data.xml",
             # "data/machine_machine_service_frequency.xml",
             "views/machine_customer_view.xml",
             "views/machine_service_views.xml",
            "views/machine_machine_tags.xml",
             "views/machine_machine_transfer.xml",
             "views/machine_machine_types.xml",
             "views/machine_machine_views.xml",
             "views/machine_machine_menus.xml",
             ],
    'author': "demo company",
    'website': "https://www.demo_company.com",
    'sequence': -10,
    'application': True,
    'installable': True,
    'auto_install': True,
}
